spring:
  application.name: gateway
  sleuth:
    enabled: true
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL}
  rabbitmq:
    host: ${rabbitmq.host}

server:
  port: 9000

zipkin:
  store:
    type: mem

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

logging:
  level:
    org.springframework.cloud: off
    org.springframework.web: off